spring:
  application:
    name: SpringStudentsApplication
  datasource:
    url: jdbc:postgresql://localhost:5252/postgres
    username: postgres
    password: abobus
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    show-sql: true
    properties:
      hibernate:
        format_sql: true
